name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  packages: write
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hydra-network/bromine
  
jobs:
  publichs:
    name: Publish
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install   

      - name: Publish
        run: bun publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  changelog:
    name: Changelog
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
